# Generated by Django 4.1 on 2022-10-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_alumni_managers_alumni_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='is_superuser',
        ),
    ]
