# Generated by Django 4.1 on 2022-10-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_remove_alumni_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
