# Generated by Django 4.1 on 2022-10-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alumni_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='is_superuser',
        ),
    ]
