# Generated by Django 4.1 on 2022-10-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_remove_alumni_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
