# Generated by Django 4.1 on 2022-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alter_alumni_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={},
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
