# Generated by Django 4.1 on 2022-10-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_alter_alumni_date_joined_alter_alumni_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
