# Generated by Django 4.1 on 2022-10-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_alter_alumni_is_active_alter_alumni_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
