# Generated by Django 4.1 on 2022-10-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0010_alter_alumni_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="profile_image",
            field=models.ImageField(default="users/default.png", upload_to="users/"),
        ),
    ]
